package util

object Constant {

    const val SPLASH_SCREEN = "SPLASH_SCREEN"
    const val HOME_SCREEN = "HOME_SCREEN"
    const val ORDER_SCREEN = "ORDER_SCREEN"
    const val EDITOR_SCREEN = "EDITOR_SCREEN"
    const val SPECIFICATION_SCREEN = "SPECIFICATION_SCREEN"
    const val SPECIFICATION_DETAIL_SCREEN = "SPECIFICATION_DETAIL_SCREEN"
    const val INVITATION_SCREEN = "INVITATION_SCREEN"
}