package ui

import androidx.compose.ui.graphics.Color

val purple = Color(0xff5F33E1)
val navigation_color = Color(0xff212121)
val background_navigation_color = Color(0xfff2f5f7)
val black = Color(0xff010101)
val light_black = Color(0xff24252C)
val light_grey = Color(0xff6E6A7C)
val light_red = Color(0xFFFFECEC)
val red = Color(0xFFFF0000)
val white = Color(0xffFFFFFF)
val background = Color(0xFFF3EFFF)
val background_arrow_color = Color(0xFFA8CAE3)
val arch = Color(0xFF2C2C2C)
val first_background = Color(0xff1F3DFF)
val second_background = Color(0xffE90713)
val third_background = Color(0xff0D7EBE)
val fourth_background = Color(0xff4CB8F5)
val fifth_background = Color(0xff2461FF)
val sixth_background = Color(0xffF19360)
val seventh_background = Color(0xffEF7D59)
val eighth_background = Color(0xffD47D39)
val ninth_background = Color(0xff7BA700)
val size_background_one = Color(0xFFE2EBFA)
val size_background_two = Color(0xFFDEF5FF)
val size_background_three = Color(0xFFE2FAED)
val size_background_four = Color(0xFFD3FFF8)